# Generated by Django 4.2.6 on 2023-10-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='number_options',
            field=models.IntegerField(null=True),
        ),
    ]
