# Generated by Django 4.2.6 on 2023-10-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_number_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
