# Generated by Django 4.2.6 on 2023-10-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_options_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='number_options',
        ),
    ]
